"""Speech generation: full-buffer and streaming chunk generation from a TTS model."""

from collections.abc import Iterator

import numpy as np
from mlx_audio.tts.utils import load

from src.tts.protocols import TTSModel


def generate_speech(model_id: str, text: str, voice: str) -> np.ndarray:
    """Generate speech audio from text using Voxtral TTS.

    Args:
        model_id: The MLX model identifier to load.
        text: The text to convert to speech.
        voice: The voice to use for synthesis.

    Returns:
        Audio samples as a numpy array at 24kHz.

    Raises:
        RuntimeError: If no audio was generated.
    """
    model = load(model_id)

    if not hasattr(model, "generate") or model.generate is None:
        msg = f"Model {model_id} does not support generation"
        raise RuntimeError(msg)

    audio_chunks: list[np.ndarray] = []
    for result in model.generate(text=text, voice=voice):
        chunk = np.array(result.audio)
        audio_chunks.append(chunk)

    if not audio_chunks:
        msg = "No audio was generated by the model"
        raise RuntimeError(msg)

    return np.concatenate(audio_chunks)


def iter_stream_chunks(model: TTSModel, text: str, voice: str, streaming_interval: float) -> Iterator[np.ndarray]:
    """Yield audio chunks incrementally as the model streams them.

    Unlike generate_chunks (which drains the whole utterance into a list before
    returning), this drives the model in streaming mode and yields each chunk as
    soon as it is decoded, so playback can start after the first chunk instead of
    after the entire utterance. Zero-length chunks (the streaming final marker
    when all frames were already emitted) are skipped.

    Args:
        model: Loaded TTS model.
        text: The text to convert to speech.
        voice: The voice to use for synthesis.
        streaming_interval: Approximate seconds of audio per streamed chunk.

    Yields:
        Audio chunks as float32 numpy arrays.
    """
    for result in model.generate(text=text, voice=voice, stream=True, streaming_interval=streaming_interval):
        chunk = np.array(result.audio, dtype=np.float32)
        if chunk.size > 0:
            yield chunk


def generate_chunks(model: TTSModel, text: str, voice: str) -> list[np.ndarray]:
    """Generate audio chunks from text without playing.

    Args:
        model: Loaded TTS model.
        text: The text to convert to speech.
        voice: The voice to use for synthesis.

    Returns:
        List of audio chunks as numpy arrays.
    """
    return [np.array(result.audio, dtype=np.float32) for result in model.generate(text=text, voice=voice)]
